### ISSUE TITLE
Improve setup instructions for the "Conversational Search" Starter Kit

### ISSUE THREAD

**Issue by andrewrfreed** [watson-developer-cloud/assistant-toolkit#134]
Existing documentation has three steps
To use the sample actions:
1. Download the sample actions from this starter kit: [ConvSearchStarter-action.json](https://github.com/watson-developer-cloud/assistant-toolkit/blob/master/integrations/extensions/starter-kits/language-model-conversational-search/ConvSearchStarter-action.json).
2. Use Actions Global Settings to upload the JSON file to your assistant. For more information, see [Uploading](https://cloud.ibm.com/docs/watson-assistant?topic=watson-assistant-admin-backup-restore#backup-restore-import).
3. Under "Variables"/"Created by you" (within the Actions page), set the discovery_project_id session variable using the project ID value you obtained [when configuring Watson Discovery above](https://github.com/watson-developer-cloud/assistant-toolkit/tree/master/integrations/extensions/starter-kits/language-model-conversational-search#configure-watson-discovery-extension).

But this yields errors, first the Actions show "Missing Extension"
<img width="1539" alt="image" src="https://github.com/watson-developer-cloud/assistant-toolkit/assets/16532202/a421372d-03d4-4b29-b033-723c9d48139b">

and the step itself shows "Extension not Fully Configured"
<img width="1105" alt="image" src="https://github.com/watson-developer-cloud/assistant-toolkit/assets/16532202/ffd4e099-5292-4dc4-9c6d-a975e0b16a21">

Will submit a PR shortly with suggested change.

**Comment by rafael-nogueras** [comment]
@andrewrfreed There should be an entire section before that that describes the setup of those extensions: are those not shown in the instructions you are reading? Could you link to the instruction page you are looking at?

**Comment by andrewrfreed** [comment]
Thanks for the support, team!

**Comment by andrewrfreed** [comment]
Update & further suggestions:
1) If the steps are followed in the order written, they work as designed.  I had imported the Action first and then the extensions, which is wrong.
2) However it is reasonable to think the order is not strict and a troubleshooting note could help
3) Some descriptive text about the sample skill would help.  It turns out that "No action matches" calls the subaction "Search" which calls the subaction "Generate Answer".
  a) Very clever :D 
  b) It is not called out that "Generate Answer" should not be called directly, since it's implementation depends on "Search"
  c) I believe you can also create an action that calls "Search" while directly setting "query_text" to pass different text to the discovery query.

**Comment by jwm4** [comment]
@rafael-nogueras made these changes (including the "further suggestions" above), and they are now delivered.  Thanks, @andrewrfreed for all the input!
