### ISSUE TITLE
Documentation unclear on how to specify URL endpoint in Watson Discovery starter kit

### ISSUE THREAD

**Issue by charleybeller** [watson-developer-cloud/assistant-toolkit#138]
Trying to follow instructions here:
https://github.com/watson-developer-cloud/assistant-toolkit/tree/master/integrations/extensions/starter-kits/language-model-conversational-search

- Provisioned a new Watson Assistant
- Set up watsonx extension
  - no issues
- Set up Watson Discovery extension:
  - manually edited openapi spec to specify url endpoint, not clear if this was correct or if there is another way to do it
  - populated project_id and version within the extension configuration in action
  - Discovery project configured as 'conversational search'
  
In Preview entering an input generates a 413 error:
<img width="645" alt="image" src="https://github.com/watson-developer-cloud/assistant-toolkit/assets/1564392/df066b97-9847-418e-b60a-00a5f9c4a7ff">

In this image the input was 'watsonx', which should pull back results from the Discovery project.
I am able to hit the Discovery project API using the Python SDK.

**Comment by charleybeller** [comment]
I solved this by configuring optional parameters in the Watson Discovery extension within the Action as in the sixth bullet point in [Setup in a new Assistant](https://github.com/watson-developer-cloud/assistant-toolkit/blob/master/integrations/extensions/starter-kits/watson-discovery/README.md#setup-in-a-new-assistant)

It appears that I would not have had to do that if I had used not done the manual editing of the OpenAPI spec to insert the url endpoint.

 Is there another way to specify the URL endpoint?

**Comment by jwm4** [comment]
Hi.  The instructions for specifying the URL endpoint were recently updated to be (hopefully) clearer.  The new instructions are listed here: https://github.com/watson-developer-cloud/assistant-toolkit/tree/master/integrations/extensions/starter-kits/language-model-conversational-search#configure-watson-discovery-extension

Do you think this would have avoided your issue?  The UX looks like this:

<img width="1239" alt="image" src="https://github.com/watson-developer-cloud/assistant-toolkit/assets/11746051/e24edc0f-5c96-4d12-b2ce-d4db4b8e16af">

(With the endpoint part at the bottom).  Do you think it is worth adding a screenshot like this to clarify?

**Comment by charleybeller** [comment]
Yes, a screenshot may be helpful. Maybe update the text as well:

> - Also fill in the portions of the URL for your instance after https:// in the discovery_url field.

Perhaps:
- At the bottom of the Authentication pane under `discovery_url` fill in` the URL for your Discovery instance

**Comment by rafael-nogueras** [comment]
This will be fixed in [this PR](https://github.com/watson-developer-cloud/assistant-toolkit/pull/139).

**Comment by jwm4** [comment]
PR is merged, fixing this issue.
