### ISSUE TITLE
Need to document requirements for Milvus integration

### ISSUE THREAD

**Issue by andrewrfreed** [watson-developer-cloud/assistant-toolkit#142]
>In this example, we use Milvus to search a document collection that we previously indexed with [this python script](https://github.com/watson-developer-cloud/assistant-toolkit/blob/master/integrations/extensions/starter-kits/language-model-conversational-search/index-with-milvus.py). We include this script as an example for reference.

`requirements.txt` would be great, I needed to run:
```
pip install PyPDF2
pip install langchain
pip install huggingface_hub
pip install pymilvus
```

**Comment by jwm4** [comment]
@mdswift [completed this](https://github.com/watson-developer-cloud/assistant-toolkit/pull/143) and also clarified the distinction between the REST and gRPC ports for Milvus (because the extension uses the former and the ingestion program uses the latter).
