### ISSUE TITLE
MetaWeather Basic example - consolidated_weather not supported

### ISSUE THREAD

**Issue by VictorLFandino** [watson-developer-cloud/assistant-toolkit#22]
Hello

When I import the action json file, I get a warning indicating that the support for arrays is limited and that the consolidated_weather array cannot be imported. Consequently, the action step cannot read the expected values and no null values are returned

![image](https://user-images.githubusercontent.com/10167356/166509984-2b745e07-4109-44ac-868d-c8f4cec2bb24.png)

Thank you

**Comment by amiddavid** [comment]
The action should be able to read any other response property.

**Comment by TazmanianDI** [comment]
Unfortunately it seems that metaweather.com no longer exists and thus this example is no longer any good. We are in the process of trying to replace it with something else but this import is never going to work again.

**Comment by TazmanianDI** [comment]
Actually let me re-open until we remove the example.

**Comment by TazmanianDI** [comment]
The example has a note in it and no response from the OP after David's response.
