### ISSUE TITLE
IBM watson custom button

### ISSUE THREAD

**Issue by Noufxx** [watson-developer-cloud/assistant-toolkit#67]
When I implanted the code it worked, but the title of the options does not show and if an option leads to another option is displays this message 

Would you like to end our coonversation?

<button id="bitton-yes"onclick="yesBye();" >Yes

<img width="167" alt="image" src="https://user-images.githubusercontent.com/105659916/197378572-82734220-168e-4e8d-9fd4-c437c6643ddc.png">

**Comment by TazmanianDI** [comment]
I think we need to see more code than what you've pasted there. I don't really understand what you are showing me. It seems likely the HTML you are using is not complete. Can you paste in all the relevant code you are using.

Also, creating a GitHub issue isn't really the right way to ask questions. These are meant for reporting bug or issues with the toolkit. If you have questions, you can ask in the IBM Watson Assistant community: https://community.ibm.com/community/user/watsonai/communities/community-home/digestviewer?CommunityKey=7a3dc5ba-3018-452d-9a43-a49dc6819633

Or you can always try asking a question on stackoverflow and tag it with watson-assistant.
